name: Debug SSH Connection

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  debug-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Test SSH Connection
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Print the SSH key (remove after confirming the key is correct)
          echo "SSH Key being used:"
          cat ~/.ssh/id_rsa

          # Attempt SSH connection
          ssh -o StrictHostKeyChecking=no -p 3022 8551@gate.jpc.infomaniak.com "echo 'SSH connection established'"
