name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust Node.js version as needed

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
         

      - name: Add SSH Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Test SSH Connection
        run: ssh -v -o StrictHostKeyChecking=no -p 3022 8551@gate.jpc.infomaniak.com "echo 'SSH connection test'"

      - name: Deploy to server
        run: |
          # Create directory on server if it doesn't exist
          ssh -o StrictHostKeyChecking=no -p 3022 8551@gate.jpc.infomaniak.com "mkdir -p /home/jelastic/ROOT"

          # Copy build files to server using SCP
          scp -o StrictHostKeyChecking=no -P 3022 -r client/build 8551@gate.jpc.infomaniak.com:/home/jelastic/ROOT
