name: Print SSH Private Key

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  print-key:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print SSH Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Printing SSH Private Key..."
          echo "${SSH_PRIVATE_KEY}"