name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust Node.js version as needed

      - name: Install dependencies and build
        run: |
          cd client  # Assuming client directory contains your React application
          npm install
          npm run build

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Create SSH directory and set permissions
          mkdir -p ~/.ssh
          
          # Decode the SSH private key and store it in id_rsa
          echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Debug - Print SSH Key for verification (remove this after confirming the key is correct)
          echo "SSH Key being used:"
          cat ~/.ssh/id_rsa

          # Debug - Check SSH connection
          ssh -o StrictHostKeyChecking=no -p 3022 8551@gate.jpc.infomaniak.com "echo 'SSH connection established'"

          # Create directory on server if it doesn't exist
          ssh -o StrictHostKeyChecking=no -p 3022 8551@gate.jpc.infomaniak.com "mkdir -p ~/my-app"

          # Copy build files to server using SCP
          scp -o StrictHostKeyChecking=no -P 3022 -r client/build 8551@gate.jpc.infomaniak.com:~/my-app

          # Optional: Restart server or any other post-deployment tasks
          # ssh -o StrictHostKeyChecking=no -p 3022 8551@gate.jpc.infomaniak.com "systemctl restart my-app.service"
