name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh

      - name: Add SSH Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Simulate User Input
        run: echo "3" > selected_option.txt

      - name: Read Selected Option
        id: read_option
        run: |
          option=$(cat selected_option.txt)
          echo "::set-output name=selected_option::$option"

      - name: Select Environment
        run: |
          selected_option=${{ steps.read_option.outputs.selected_option }}
          case $selected_option in
            0)
              echo "Exiting deployment process."
              exit 0
              ;;
            1)
              echo "Refreshing environment list."
              # Add commands to refresh environment list if needed
              ;;
            2)
              echo "Performing actions for [My First Project] [0]:(0)."
              # Add commands specific to [My First Project] [0]:(0) environment
              ;;
            3)
              echo "Performing actions for env-5868270.jcloud.ik-server.com."
              ssh -o StrictHostKeyChecking=no -p 3022 8551@gate.jpc.infomaniak.com "mkdir -p /home/jelastic/ROOT"
              scp -o StrictHostKeyChecking=no -P 3022 -r client/build 8551@gate.jpc.infomaniak.com:/home/jelastic/ROOT
              ;;
            *)
              echo "Invalid option selected."
              exit 1
              ;;
          esac
