name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa gate.jpc.infomaniak.com >> ~/.ssh/known_hosts

      - name: Select Environment
        id: select_environment
        run: echo "3" > selected_environment.txt

      - name: Read Selected Environment
        run: |
          environment=$(cat selected_environment.txt)
          echo "Selected Environment: $environment"

      - name: Deploy to Selected Environment
        if: ${{ steps.select_environment.outputs.environment == '3' }}
        run: |
          ssh -o StrictHostKeyChecking=no -p 3022 8551@gate.jpc.infomaniak.com "mkdir -p /home/jelastic/ROOT"
          scp -o StrictHostKeyChecking=no -P 3022 -r client/build 8551@gate.jpc.infomaniak.com:/home/jelastic/ROOT
